-- MySQL Script generated by MySQL Workbench
-- Fri Jun 24 12:27:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema geo_hsp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `geo_hsp` ;

-- -----------------------------------------------------
-- Schema geo_hsp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `geo_hsp` DEFAULT CHARACTER SET utf8 ;
USE `geo_hsp` ;

-- -----------------------------------------------------
-- Table `geo_hsp`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geo_hsp`.`country` ;

CREATE TABLE IF NOT EXISTS `geo_hsp`.`country` (
  `idCountry` INT(16) NOT NULL,
  `name_country` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idCountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geo_hsp`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geo_hsp`.`department` ;

CREATE TABLE IF NOT EXISTS `geo_hsp`.`department` (
  `idDepartment` INT(16) NOT NULL,
  `name_department` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idDepartment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geo_hsp`.`georeference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geo_hsp`.`georeference` ;

CREATE TABLE IF NOT EXISTS `geo_hsp`.`georeference` (
  `idGeoreference` INT(16) NOT NULL AUTO_INCREMENT,
  `latitude` FLOAT NULL,
  `longitude` FLOAT NULL,
  PRIMARY KEY (`idGeoreference`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geo_hsp`.`municipality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geo_hsp`.`municipality` ;

CREATE TABLE IF NOT EXISTS `geo_hsp`.`municipality` (
  `idCity` INT(16) NOT NULL,
  `name_city` VARCHAR(32) NOT NULL,
  `department_id` INT(16) NOT NULL,
  `country_id` INT(16) NOT NULL,
  PRIMARY KEY (`idCity`),
  CONSTRAINT `idDepartment`
    FOREIGN KEY (`department_id`)
    REFERENCES `geo_hsp`.`department` (`idDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCountry`
    FOREIGN KEY (`country_id`)
    REFERENCES `geo_hsp`.`country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idDepartment_idx` ON `geo_hsp`.`municipality` (`department_id` ASC) VISIBLE;

CREATE INDEX `idCountry_idx` ON `geo_hsp`.`municipality` (`country_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `geo_hsp`.`petitioner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geo_hsp`.`petitioner` ;

CREATE TABLE IF NOT EXISTS `geo_hsp`.`petitioner` (
  `idHSP` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_hsp` VARCHAR(128) NOT NULL,
  `status_id` TINYINT NOT NULL DEFAULT 1,
  `pac` BIGINT UNSIGNED NOT NULL,
  `tin` BIGINT UNSIGNED NOT NULL,
  `city_id` INT(16) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `georeference_id` INT(16) NULL,
  `phone` VARCHAR(64) NOT NULL,
  `cell` VARCHAR(64) NOT NULL,
  `name_contact` VARCHAR(128) NOT NULL,
  `lastname_contact` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `working_hours` VARCHAR(64) NOT NULL,
  `service_id` INT(16) NOT NULL,
  `update_at` DATETIME NOT NULL DEFAULT on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idHSP`),
  CONSTRAINT `idStatus`
    FOREIGN KEY (`status_id`)
    REFERENCES `geo_hsp`.`status` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCity`
    FOREIGN KEY (`city_id`)
    REFERENCES `geo_hsp`.`municipality` (`idCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idGeoreference`
    FOREIGN KEY (`georeference_id`)
    REFERENCES `geo_hsp`.`georeference` (`idGeoreference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idService`
    FOREIGN KEY (`service_id`)
    REFERENCES `geo_hsp`.`service` (`idService`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idStatus_idx` ON `geo_hsp`.`petitioner` (`status_id` ASC) VISIBLE;

CREATE INDEX `idCity_idx` ON `geo_hsp`.`petitioner` (`city_id` ASC) VISIBLE;

CREATE INDEX `idGeoreference_idx` ON `geo_hsp`.`petitioner` (`georeference_id` ASC) VISIBLE;

CREATE INDEX `idService_idx` ON `geo_hsp`.`petitioner` (`service_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `geo_hsp`.`service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geo_hsp`.`service` ;

CREATE TABLE IF NOT EXISTS `geo_hsp`.`service` (
  `idService` INT(16) NOT NULL AUTO_INCREMENT,
  `name_service` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idService`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geo_hsp`.`service_for_petitioner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geo_hsp`.`service_for_petitioner` ;

CREATE TABLE IF NOT EXISTS `geo_hsp`.`service_for_petitioner` (
  `id` INT(16) NOT NULL AUTO_INCREMENT,
  `service_id` INT(16) NOT NULL,
  `hsp_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_service_has_petitioner_service1`
    FOREIGN KEY (`service_id`)
    REFERENCES `geo_hsp`.`service` (`idService`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_has_petitioner_petitioner1`
    FOREIGN KEY (`hsp_id`)
    REFERENCES `geo_hsp`.`petitioner` (`idHSP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_service_has_petitioner_petitioner1_idx` ON `geo_hsp`.`service_for_petitioner` (`hsp_id` ASC) VISIBLE;

CREATE INDEX `fk_service_has_petitioner_service1_idx` ON `geo_hsp`.`service_for_petitioner` (`service_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `geo_hsp`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geo_hsp`.`status` ;

CREATE TABLE IF NOT EXISTS `geo_hsp`.`status` (
  `idStatus` TINYINT(1) NOT NULL DEFAULT 1,
  `status_hsp` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idStatus`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
